DEFAULT_DATA_ATTRIBUTE_KEYS = ['concept:endpoint', 'cpee:activity_uuid']

DEFAULT_CONFIG = {
    'latent_dim': 32,
    'hidden_dims': [128, 64],
    'window_size': 10,
    'n_min': 15,
    'n_reliable': 40,
    'alpha': 0.5,
    'fuzzifier': 2.0,
    'lambda_exp': 1.0,
    'sparsity_lambda': 0.01,
    'noise_std': 0.1,
    'warmup_events': 1000,
    'embedding_dim': 8,
    'max_lifecycle_categories': 20,
    'training_epochs': 100,
    'learning_rate': 0.001,
    'auto_calibrate': False,
    'confidence_mode': 'entropy',
    'delta': 2.0,
    'retrain_interval': 1000,
    'enable_synthetic_reconciliation': True,
    'synthetic_merge_threshold': 2.0,
    'drift_decay_factor': 0.5,
    'cf_feature_mode': 'prev_only',
    'disable_iot_features': False,
    'undiscovered_n_new': 10,
    'undiscovered_persist_time': 5,
    'undiscovered_separation': 3.0,
    'candidate_match_threshold': 2.0,
    'candidate_min_members': 3,
    'candidate_max_members_stored': 200,
    'epsilon': 1e-4,
}

DATASET_CONFIGS = {
    'chess': {
        **DEFAULT_CONFIG,
        'warmup_events': 3000,
        'n_min': 20,
        'n_reliable': 50,
        'warmup_stability_window': 1000,
        'data_attribute_keys': ['concept:endpoint', 'cpee:activity_uuid'],
    },
    'cottoncandy': {
        **DEFAULT_CONFIG,
        'warmup_events': 7000,
        'warmup_stability_window': 5000,
        'data_attribute_keys': ['concept:endpoint', 'cpee:activity_uuid'],
        'enable_sequence_head': False,
    },
    'cyberseciot': {
        **DEFAULT_CONFIG,
        'warmup_events': 2000,
        'latent_dim': 48,
        'hidden_dims': [256, 128],
        'data_attribute_keys': ['org:resource', 'process:exe', 'process:path'],
        'enable_sequence_head': True,
        'window_size': 20,
        'sequence_hidden_dim': 128,
        'sequence_num_layers': 2,
        'alpha_seq': 0.30,
        'enable_count_cache': True,
        'count_cache_order': 3,
    },
    'mimiciv': {
        **DEFAULT_CONFIG,
        'warmup_events': 5000,
        'latent_dim': 64,
        'hidden_dims': [256, 128],
        'data_attribute_keys': ['org:resource', 'measurement_context', 'category'],
        'enable_sequence_head': False,
    },
    'smartfactory': {
        **DEFAULT_CONFIG,
        'warmup_events': 5000,
        'warmup_stability_window': 1000,
        'data_attribute_keys': ['requested_service_url', 'lifecycle:state', 'current_task'],
        'enable_sequence_head': False,
    },
    'vienna': {
        **DEFAULT_CONFIG,
        'warmup_events': 2000,
        'latent_dim': 64,
        'hidden_dims': [256, 128],
        'data_attribute_keys': [],
        'enable_sequence_head': True,
        'enable_count_cache': True,
        'count_cache_order': 3,
        'window_size': 20,
        'sequence_hidden_dim': 128,
        'sequence_num_layers': 2,
        'alpha_seq': 0.30,
    },
    'bpic2013_closed': {
        **DEFAULT_CONFIG, 'warmup_events': 1000,
        'data_attribute_keys': ['org:group', 'org:role', 'organization involved'],
        'disable_iot_features': True, 'enable_sequence_head': True,
        'enable_count_cache': True, 'count_cache_order': 3,
    },
    'bpic2013_open': {
        **DEFAULT_CONFIG, 'warmup_events': 500,
        'data_attribute_keys': ['org:group', 'org:role', 'organization involved'],
        'disable_iot_features': True, 'enable_sequence_head': True,
        'enable_count_cache': True, 'count_cache_order': 3,
    },
    'bpic2013_incidents': {
        **DEFAULT_CONFIG, 'warmup_events': 10000,
        'data_attribute_keys': ['org:group', 'org:role', 'organization involved', 'impact'],
        'disable_iot_features': True, 'enable_sequence_head': True,
        'enable_count_cache': True, 'count_cache_order': 3,
    },
    'bpic2012': {
        **DEFAULT_CONFIG, 'warmup_events': 40000,
        'latent_dim': 48, 'hidden_dims': [256, 128],
        'data_attribute_keys': ['AMOUNT_REQ', 'org:resource'],
        'disable_iot_features': True, 'enable_sequence_head': True,
        'enable_count_cache': True, 'count_cache_order': 3,
    },
    'bpic2017': {
        **DEFAULT_CONFIG, 'warmup_events': 200000,
        'latent_dim': 64, 'hidden_dims': [256, 128],
        'data_attribute_keys': ['Action', 'ApplicationType', 'LoanGoal', 'Selected',
                                 'Accepted', 'org:resource', 'EventOrigin'],
        'disable_iot_features': True, 'enable_sequence_head': True,
        'enable_count_cache': True, 'count_cache_order': 3,
    },
    'bpic2020_domestic': {
        **DEFAULT_CONFIG, 'warmup_events': 8000,
        'data_attribute_keys': ['Amount', 'BudgetNumber', 'org:resource', 'Permit'],
        'disable_iot_features': True, 'enable_sequence_head': True,
        'enable_count_cache': True, 'count_cache_order': 3,
    },
    'bpic2020_international': {
        **DEFAULT_CONFIG, 'warmup_events': 10000,
        'data_attribute_keys': ['Amount', 'BudgetNumber', 'org:resource', 'Permit'],
        'disable_iot_features': True, 'enable_sequence_head': True,
        'enable_count_cache': True, 'count_cache_order': 3,
    },
    'bpic2020_permit': {
        **DEFAULT_CONFIG, 'warmup_events': 12000,
        'data_attribute_keys': ['Amount', 'BudgetNumber', 'org:resource', 'Permit'],
        'disable_iot_features': True, 'enable_sequence_head': True,
        'enable_count_cache': True, 'count_cache_order': 3,
    },
    'bpic2020_prepaid': {
        **DEFAULT_CONFIG, 'warmup_events': 3000,
        'data_attribute_keys': ['Amount', 'BudgetNumber', 'org:resource', 'Permit'],
        'disable_iot_features': True, 'enable_sequence_head': True,
        'enable_count_cache': True, 'count_cache_order': 3,
    },
    'bpic2020_request': {
        **DEFAULT_CONFIG, 'warmup_events': 6000,
        'data_attribute_keys': ['Amount', 'BudgetNumber', 'org:resource', 'Permit'],
        'disable_iot_features': True, 'enable_sequence_head': True,
        'enable_count_cache': True, 'count_cache_order': 3,
    },
    'sepsis': {
        **DEFAULT_CONFIG, 'warmup_events': 3000,
        'data_attribute_keys': ['org:group', 'InfectionSuspected', 'DiagnosticBlood',
                                 'Hypotensie', 'Hypoxie', 'SIRSCritTachypnea',
                                 'SIRSCritHeartRate', 'SIRSCritTemperature'],
        'disable_iot_features': True, 'enable_sequence_head': True,
        'enable_count_cache': True, 'count_cache_order': 3,
    },
    'road_traffic_fine': {
        **DEFAULT_CONFIG, 'warmup_events': 80000,
        'latent_dim': 48, 'hidden_dims': [256, 128],
        'data_attribute_keys': ['amount', 'paymentAmount', 'totalPaymentAmount',
                                 'org:resource', 'dismissal', 'vehicleClass'],
        'disable_iot_features': True, 'enable_sequence_head': True,
        'enable_count_cache': True, 'count_cache_order': 3,
    },
    'wabo': {
        **DEFAULT_CONFIG, 'warmup_events': 1500,
        'data_attribute_keys': ['org:resource', 'org:group'],
        'disable_iot_features': True, 'enable_sequence_head': True,
        'enable_count_cache': True, 'count_cache_order': 3,
    },
    'helpdesk': {
        **DEFAULT_CONFIG, 'warmup_events': 3000,
        'data_attribute_keys': ['seriousness', 'customer', 'product', 'responsible_section',
                                 'service_level', 'service_type', 'support_section', 'workgroup'],
        'disable_iot_features': True, 'enable_sequence_head': True,
        'enable_count_cache': True, 'count_cache_order': 3,
    },
}

def get_config(dataset_name):
    config = DATASET_CONFIGS.get(dataset_name, DEFAULT_CONFIG).copy()
    return config
